#include <stdio.h>

/* This is generated by a template program */

void copy(char *i, char *o){

   do {
        *i++ = *o++;
    }while(*o != '\0');
    *i = '\0';

   return ;
}

void copy_v2(char i[], char o[]){

   do {
        *i++ = *o++;
    }while(*o != '\0');
    *i = '\0';

   return ;
}

int len(char *ch){

    int i = 1;
    for( ; *++ch != '\0'; i++);

    return i;
}

void attach(char *str1, char *str2){
    while( *++str1 != '\0');

    for(; *str2 != '\0' ; *str1++ = *str2++);
    *str1 = '\0';

    return;
}

char* find(char *str, char ch){

    for(; *str != ch ; str++ );
    return str;
}

int main(){

    char name[24] = "Pavan", dummy[24], last[12]= "Boorla", *fstring;

    copy(dummy, name);
    printf("Name:%s Copy:%s len:%d\n", dummy, name, len(name));

    attach(name, last);
    printf("Attached name: %s\n", name);

    fstring = find(name, 'B');
    printf("fstring: %s\n", fstring);

    copy(fstring, "Kumar");
    printf("Name: %s\n", name);

return 0;
}
